### ISSUE TITLE
Fine-grained action types

### ISSUE THREAD

**Issue by feketegy** [websitesfortrello/trello-webhooks#4]
Just a suggestion: 

There's a `translationKey` property under the `display` property in each action. 

It is some sort of sub type for the action like if the action type is `updateBoard` and the `translationKey` is `action_update_board_name` it means the board name was changed.

From this you'll know what action happened exactly. The translationKey is not documented anywhere in the Trello docs., so I'm not sure how reliable it is.

**Comment by fiatjaf** [comment]
I've seen that now. In the time I created this repository that `translationKey` didn't exist at all.

However I think it's better to rely on the `old` field to know what changed, like here:
https://github.com/fiatjaf/trello-webhooks/blob/b0c936b3621d7a5f31cdb07f9e49b7203a18580b/board-name.json#L10-L12
